test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

      exclude = ["change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------